require 'rubygems'
require 'vkontakte_api'
require 'digest'
require 'mechanize'

require 'vk_market/version'
require 'vk_market/auth'
require 'vk_market/market'
require 'vk_market/product'
require 'vk_market/photo'
require 'vk_market/album'
require 'vk_market/products_set'
